"""
12 — Digital Twin dataset test (standalone).

Tests our pipeline against the MultiPatient Elderly Respiration dataset
(Mendeley vm8j5dvrxy). 14 paced rates × 30 "patients" = 420 files.

Important context (from the paper, Comput Biol Med 2023):
  - Single real subject; 30 patients are synthetic, generated by
    statistical time-series augmentation.
  - Source rate 120 PPS, same 3m × 3m room as Alzaabi 2024.
  - CSV files store pre-extracted amplitude only: 52 columns × ~12006
    rows of float amplitudes. No timestamps, no complex CSI.

What this test can answer:
  - Does our pipeline scale to many more files at the same MAE?
  - Do augmented samples behave like real ones?

What it CANNOT answer:
  - Cross-room / cross-environment generalization (still same lab).

Two pipelines tested:
  - paper_mode (replication of Alzaabi 2024 + auto-prominence PC pick)
  - enhanced (amplitude-only fallback; no CSI ratio because we don't
    have complex data)
Both are reimplemented inline here from csi_pipeline.py helpers, so
this script doesn't touch the production pipeline's public API.
"""
from pathlib import Path
import sys
import re
import numpy as np
import pandas as pd
from scipy import signal

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / 'notebooks'))
from csi_pipeline import (
    hampel_columns, bandpass, peak_bpm, dwt_band_filter, poly_detrend,
)

DATA = (ROOT / 'datasets' /
        'MultiPatient Elderly Respiration dataset in Digital Twin Technology' /
        'All Patient BPM Data')
SOURCE_FS_NOMINAL = 120.0  # paper says 120 PPS, but observed varies
RECORDING_DURATION_S = 120.0  # paper: 2 minutes per recording
TARGET_FS_PAPER = 40.0
TARGET_FS_ENH   = 20.0


def load_amp_csv(path):
    """Returns (n_packets, 52) amplitude matrix."""
    df = pd.read_csv(path, header=None)
    return df.to_numpy(dtype=np.float32)


def estimate_paper_mode(amp, src_fs):
    """Faithful paper_mode applied to pre-extracted amplitude.

    Steps: Fourier resample to 40 Hz → DWT D6+D7 → PCA on all 52 →
    prominence-based pick of PC1 vs PC2 → PSD peak BPM."""
    band = (0.15625, 0.625)
    fs_target = TARGET_FS_PAPER
    n_target = int(round(amp.shape[0] * fs_target / src_fs))
    feats_u = signal.resample(amp, n_target, axis=0)
    feats_b = dwt_band_filter(feats_u, fs_target).astype(np.float32)
    X = (feats_b - feats_b.mean(0)) / (feats_b.std(0) + 1e-9)
    U, S, Vt = np.linalg.svd(X, full_matrices=False)
    nperseg = min(X.shape[0], int(fs_target * 60))

    def prominence(idx):
        pc = U[:, idx] * S[idx]
        f, P = signal.welch(pc, fs=fs_target, nperseg=nperseg)
        m = (f >= band[0]) & (f <= band[1])
        if not m.any():
            return 0.0
        return float(P[m].max() / (np.median(P[m]) + 1e-12))

    proms = [prominence(i) for i in range(min(2, U.shape[1]))]
    pc_idx = int(np.argmax(proms))
    fused = U[:, pc_idx] * S[pc_idx]
    bpm, _ = peak_bpm(fused, fs_target, lo=band[0], hi=band[1],
                      nperseg=nperseg, harmonic_guard=False)
    return bpm


def estimate_enhanced(amp, src_fs):
    """Enhanced path adapted to amplitude-only input (no CSI ratio
    because we don't have complex CSI). Hampel → linear interp resample
    to 20 Hz → polynomial detrend → Butterworth 0.1–0.7 Hz → variance-rank
    top quartile → PC1 → PSD peak with harmonic guard."""
    band = (0.1, 0.7)
    fs_target = TARGET_FS_ENH
    feats = hampel_columns(amp, win=11, n_sigmas=3.0)
    n_target = int(round(feats.shape[0] * fs_target / src_fs))
    feats_u = signal.resample(feats, n_target, axis=0).astype(np.float32)
    feats_b = bandpass(poly_detrend(feats_u, 3, axis=0),
                       fs_target, band[0], band[1])
    in_band = feats_b.var(axis=0)
    k_keep = max(4, in_band.size // 4)
    top = np.argsort(in_band)[-k_keep:]
    X = feats_b[:, top]
    X = (X - X.mean(0)) / (X.std(0) + 1e-9)
    U, S, Vt = np.linalg.svd(X, full_matrices=False)
    fused = U[:, 0] * S[0]
    nperseg = min(X.shape[0], int(fs_target * 60))
    bpm, _ = peak_bpm(fused, fs_target, lo=band[0], hi=band[1],
                      nperseg=nperseg, harmonic_guard=True)
    return bpm


def collect_files():
    out = []
    for d in sorted(DATA.glob('*BPM data')):
        m = re.match(r'(\d+)BPM data', d.name)
        if not m:
            continue
        target = int(m.group(1))
        for csv in sorted(d.glob('*.csv'), key=lambda p: int(re.search(r'P(\d+)', p.stem).group(1))):
            patient = int(re.search(r'P(\d+)', csv.stem).group(1))
            out.append((target, patient, csv))
    return out


files = collect_files()
print(f'Found {len(files)} files across {len(set(f[0] for f in files))} BPM rates × {len(set(f[1] for f in files))} patients')

rows = []
for i, (tgt, pat, path) in enumerate(files):
    amp = load_amp_csv(path)
    # Per-file source rate from row count (paper recordings = 2 min each).
    src_fs = amp.shape[0] / RECORDING_DURATION_S
    try:
        bpm_p = estimate_paper_mode(amp, src_fs)
        bpm_e = estimate_enhanced(amp, src_fs)
    except Exception as e:
        print(f'  P{pat}-{tgt}: FAILED ({e})')
        continue
    rows.append({
        'tgt': tgt, 'patient': pat,
        'paper_bpm': bpm_p, 'enh_bpm': bpm_e,
        'paper_err': abs(bpm_p - tgt),
        'enh_err':   abs(bpm_e - tgt),
    })
    if (i + 1) % 50 == 0:
        print(f'  ... {i+1}/{len(files)}')

# Summary
import collections
arr_p = np.array([r['paper_err'] for r in rows])
arr_e = np.array([r['enh_err']   for r in rows])
print(f'\n=== {len(rows)} files ===')
print(f'paper_mode  MAE {arr_p.mean():.3f}   max {arr_p.max():.2f}   '
      f'≤0.25 {int((arr_p<=0.25).sum())}/{len(arr_p)}   ≤1 {int((arr_p<=1).sum())}/{len(arr_p)}')
print(f'enhanced    MAE {arr_e.mean():.3f}   max {arr_e.max():.2f}   '
      f'≤0.25 {int((arr_e<=0.25).sum())}/{len(arr_e)}   ≤1 {int((arr_e<=1).sum())}/{len(arr_e)}')

# Per-rate breakdown
print('\nPer paced-BPM:')
print(f'  {"BPM":>4}  {"n":>3}  {"paper MAE":>10}  {"paper max":>10}  '
      f'{"enh MAE":>9}  {"enh max":>9}')
by_rate = collections.defaultdict(list)
for r in rows:
    by_rate[r['tgt']].append(r)
for tgt in sorted(by_rate):
    sub = by_rate[tgt]
    p_e = np.array([r['paper_err'] for r in sub])
    e_e = np.array([r['enh_err']   for r in sub])
    print(f'  {tgt:>4}  {len(sub):>3}  '
          f'{p_e.mean():>10.3f}  {p_e.max():>10.2f}  '
          f'{e_e.mean():>9.3f}  {e_e.max():>9.2f}')

# Per-patient breakdown (single subject augmented 30 ways, so this
# tells us how much variation the augmentation introduces)
print('\nWorst 5 patients (paper_mode MAE across rates):')
by_pat = collections.defaultdict(list)
for r in rows:
    by_pat[r['patient']].append(r['paper_err'])
worst = sorted(by_pat.items(), key=lambda kv: -np.mean(kv[1]))[:5]
for pat, errs in worst:
    print(f'  P{pat}: MAE {np.mean(errs):.3f}  max {np.max(errs):.2f}  (n={len(errs)})')
